{"uuid":"4f488842-7fbf-4c56-8fed-b79facffcfc0","historyId":"86e94da1ee80740ea94a7ee7b0f81807","fullName":"com.tester.ex03_Selenium_Locators.TestSelenium_11_Task.test_vwo_free_trial","labels":[{"name":"package","value":"com.tester.ex03_Selenium_Locators.TestSelenium_11_Task"},{"name":"testClass","value":"com.tester.ex03_Selenium_Locators.TestSelenium_11_Task"},{"name":"testMethod","value":"test_vwo_free_trial"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LearningSeleniumATB13x"},{"name":"subSuite","value":"com.tester.ex03_Selenium_Locators.TestSelenium_11_Task"},{"name":"host","value":"KASAM"},{"name":"thread","value":"21580@KASAM.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Kajal"}],"links":[],"name":"test_vwo_free_trial","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Compound class names not permitted\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception\nBuild info: version: '4.35.0', revision: '1c58e5028b'\nSystem info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'\nDriver info: driver.version: unknown","trace":"org.openqa.selenium.InvalidSelectorException: Compound class names not permitted\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception\nBuild info: version: '4.35.0', revision: '1c58e5028b'\nSystem info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.By$ByClassName.<init>(By.java:313)\r\n\tat org.openqa.selenium.By.className(By.java:103)\r\n\tat com.tester.ex03_Selenium_Locators.TestSelenium_11_Task.test_vwo_free_trial(TestSelenium_11_Task.java:23)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"TC#1 - Verify that invalid login, error message is","steps":[],"attachments":[],"parameters":[],"start":1756464872175,"stop":1756464879931}